config/routes.rb
Rails.application.routes.draw do
  
  resources :courses
  resources :dojos
  devise_for :judokas, controllers: {
    registrations:'judokas/registrations',
    sessions: 'judokas/sessions' 
  }
  devise_for :senseis, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  get 'mis_senseis', to: 'senseis#index', as: 'mis_senseis'
  get 'graphics', to: 'info#graphics', as: 'graphics'
  get 'info', to: 'info#info', as: 'info'
  get 'categories', to: 'categories#index'
  get 'judo_test', to: 'judo_test#index'
  get 'judokas', to: 'judokas#index', as: 'judokas'
  get 'judokas/:id', to: 'judokas#show', as: 'judokas_show'
  get 'senseis/:id', to: 'senseis#show', as: 'senseis_show'
  get 'judo_test/:id', to: 'judo_test#show', as: 'judo_test_show'
  
  root to: "info#lobby"
end

app/models/sensei.rb
class Sensei < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  has_many :sensei_dojos 
  has_many :dojos, through: :sensei_dojos

  has_many :sensei_courses
  has_many :courses, through: :sensei_courses

  belongs_to :level
  has_many :judo_tests

  def self.find_by_uid!(uid)
    Sensei.find_by!("name = :p OR id = :p", p: uid)
  end
end

app/controllers/senseis_controller.rb
class SenseisController < ApplicationController
  before_action :authenticate_judoka!

  def index 
    @senseis = Sensei.all
  end

  def show
    @judokas = Judoka.all
    @sensei = Sensei.find(params[:id])
  end

end

app/views/senseis/index.html.erb
<div class="">
<h1>Mis Senseis</h1>
</div>

<table class="table p-5">
<thead class="thead-dark">
<tr>
<th>Nombre</th>
<th>ID</th>
<th colspan="3"></th>
</tr>
</thead>

<tbody>
<% @senseis.each do |sensei| %>
<tr>
<td><%= sensei.name %></td>
<td><%= sensei.id_card %></td>
<td><%= link_to 'Mostrar', senseis_show_path(sensei.id), class:'btn btn-danger' %></td>
</tr>
<% end %>
</tbody>
</table>
 <%= link_to 'Atrás', info_path, class:'btn btn-danger'  %>
<br> 

app/views/senseis/show.html.erb
<h1>Sensei</h1>

  <div class="relative_width">
    <div class="talk_text">
      <section>
        <div class="container">
          <p><strong>Nombre: </strong><%= @sensei.name %></p>
          <p><strong>Primer apellido: </strong><%= @sensei.last_name %></p>
          <p><strong>Segundo apellido: </strong><%= @sensei.surname %></p>
          <p><strong>Nacionalidad: </strong><%= @sensei.nationality %></p>
          <p><strong>Email: </strong><%= @sensei.email %></p>
          <p><strong>Número de tel: </strong><%= @sensei.phone_number %></p>
        </div>
      </section>
    </div>
  </div>

<%= link_to 'Atrás', mis_senseis_path, class:'btn btn-danger'  %>