config/routes.rb
Rails.application.routes.draw do
  
  resources :courses
  resources :dojos
  devise_for :judokas, controllers: {
    registrations:'judokas/registrations',
    sessions: 'judokas/sessions' 
  }
  devise_for :senseis, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  get 'mis_senseis', to: 'senseis#index', as: 'mis_senseis'
  get 'graphics', to: 'info#graphics', as: 'graphics'
  get 'info', to: 'info#info', as: 'info'
  get 'categories', to: 'categories#index'
  get 'judo_test', to: 'judo_test#index'
  get 'judokas', to: 'judokas#index', as: 'judokas'
  get 'judokas/:id', to: 'judokas#show', as: 'judokas_show'
  get 'senseis/:id', to: 'senseis#show', as: 'senseis_show'
  get 'judo_test/:id', to: 'judo_test#show', as: 'judo_test_show'
  
  root to: "info#lobby"
end

app/models/judoka.rb
class Judoka < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_accessor :categories
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :dojo
  belongs_to :level

  has_one_attached :photo
  
  has_many :judo_tests
  has_many :judoka_courses
  has_many :courses, through: :judoka_courses

  def self.find_by_uid!(uid)
    Judoka.find_by!("name = :p OR id = :p", p: uid)
  end
end

app/controllers/judokas/registrations_controller.rb
# frozen_string_literal: true

class Judokas::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @dojos = Dojo.all 
    @types = ['national', 'resident', 'foreign']
    @categories = Category.all
    @judo_tests = JudoTest.all
    @levels = Level.all.pluck(:name, :id)
    super
  end

  # POST /resource
  def create
    @dojos = Dojo.all   
    @types = ['national', 'resident', 'foreign']
    @judo_tests = JudoTest.all
    @levels = Level.all.pluck(:name, :id)
    @categories = Category.all    
    super
  end 
  
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  #If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:dojo_id, :name, :last_name, :surname, :date_of_birth, :id_type, :nationality, :id_card, :address, :phone_number, :parental_or_responsibility, :start_date, :photo, :level_id])
  end

  def after_sign_in_path_for(resource)
    judokas_show_path(current_judoka)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/judokas/sessions_controller.rb
# frozen_string_literal: true

class Judokas::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_in_path_for(resource)
    judokas_show_path(current_judoka)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/judokas_controller.rb
class JudokasController < ApplicationController
  before_action :authenticate_judoka!  

  def index
    @judokas = Judoka.all
  end

  def show
    @judokas = Judoka.all
    @judoka = Judoka.find(params[:id])
  end

end

app/views/judokas/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-light bg-warning">
  <%= link_to root_path, class: 'navbar-brand' do %>
     <%= image_tag asset_path('logo.png'), size: "80x80"%>
  <% end %> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Dojos', dojos_path, class: 'nav-link active' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Cursos', courses_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Judokas', new_judoka_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Judo Tests', judo_test_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup><a class="nav-link disabled " href="#" tabindex="-1" aria-disabled="true">
      </a>
      <div class="dropdown-menu" aria-labelledby="dropdown01">
      <a class="dropdown-item" href="#">
      <% if judoka_signed_in? %>
      <%= link_to 'Desconectarse', destroy_judoka_session_path, method: :delete%>
      <% else %>
      <%= link_to '(Iniciar Sesion con Judoka)', new_judoka_session_path %>
      <%= link_to '(Iniciar Sesion con Sensei)', new_sensei_session_path %>
        <%end %>
      </div>
        </li>
      <%if current_judoka %>
      <li class="nav-item">
      <a class="nav-link disabled text-light" href="#" tabindex="-1" aria-disabled="true"><%= current_judoka.email %></a>
      </li>
      <%end%>
    </ul>
  </div>
</nav>

app/views/judokas/index.html.erb
<h1>Judokas</h1>

<table class="table p-5">
  <thead class="thead-dark">
    <tr>
      <th>Nombre</th>
      <th>Dojo</th>
      <th>ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @judokas.each do |judoka| %>
      <tr>
        <td><%= judoka.name %></td>
        <td><%= judoka.dojo.name %></td>
        <td><%= judoka.id_card %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/judokas/show.html.erb
<section>
<%= render 'navbar' %>
</section>

<h1 class="text-center p-5">Mi Perfil</h1>
  <div class="container py-5">
  <div class="row">
    <div class="item col-sm-5 p-5 center-block">
    <% if @judoka.photo.attached? %>
      <%= image_tag @judoka.photo, size: '200x200' , class: "rounded-circle", alt: "Cinque Terre"%>
    <% end %>
    <div class="my-3 mx-5">
    <%= link_to 'Editar', edit_judoka_registration_path, class:'btn btn-danger'  %> 
    </div>
    </div>
    <div class="azul col-sm-5">
          <p><strong>Nombre: </strong><%= @judoka.name %></p>
          <p><strong>Primer apellido: </strong><%= @judoka.last_name %></p>
          <p><strong>Segundo apellido: </strong><%= @judoka.surname %></p>
          <p><strong>Fecha de nacimiento: </strong><%= @judoka.date_of_birth %></p>
          <p><strong>Tipo de identificación: </strong><%= @judoka.id_type %></p>
          <p><strong>Nacionalidad: </strong><%= @judoka.nationality %></p>
          <p><strong>Número de identificación: </strong><%= @judoka.id_card %></p>
          <p><strong>Dirección: </strong><%= @judoka.address %></p>
          <p><strong>Número de tel: </strong><%= @judoka.phone_number %></p>
          <p><strong>Encargado legal: </strong><%= @judoka.parental_or_responsibility %></p>
          <p><strong>Fecha de inicio: </strong><%= @judoka.start_date %></p>
          <%= link_to 'Información', info_path, class:'btn btn-danger'  %> 
      </div>
    </div>