config/routes.rb
Rails.application.routes.draw do
  
  resources :courses
  resources :dojos
  devise_for :judokas, controllers: {
    registrations:'judokas/registrations',
    sessions: 'judokas/sessions' 
  }
  devise_for :senseis, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  get 'mis_senseis', to: 'senseis#index', as: 'mis_senseis'
  get 'graphics', to: 'info#graphics', as: 'graphics'
  get 'info', to: 'info#info', as: 'info'
  get 'categories', to: 'categories#index'
  get 'judo_test', to: 'judo_test#index'
  get 'judokas', to: 'judokas#index', as: 'judokas'
  get 'judokas/:id', to: 'judokas#show', as: 'judokas_show'
  get 'senseis/:id', to: 'senseis#show', as: 'senseis_show'
  get 'judo_test/:id', to: 'judo_test#show', as: 'judo_test_show'
  
  root to: "info#lobby"
end

app/models/dojo.rb
class Dojo < ApplicationRecord
  has_many :sensei_dojos 
  has_many :senseis, through: :sensei_dojos

  has_many :judokas 
  has_many :courses
end

app/controllers/dojos_controller.rb
class DojosController < ApplicationController
  before_action :set_dojo, only: %i[ show edit update destroy ]
  before_action :authenticate_judoka!

  # GET /dojos or /dojos.json
  def index
    @dojos = Dojo.all
  end

  # GET /dojos/1 or /dojos/1.json
  def show
    respond_to do |format|
      format.js { render layout: false }
      format.html { render :show }
    end
  end

  # GET /dojos/new
  def new
    @dojo = Dojo.new
  end

  # GET /dojos/1/edit
  def edit
  end

  # POST /dojos or /dojos.json
  def create
    @dojo = Dojo.new(dojo_params)

    respond_to do |format|
      if @dojo.save
        format.html { redirect_to @dojo, notice: "Dojo was successfully created." }
        format.json { render :show, status: :created, location: @dojo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dojo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dojos/1 or /dojos/1.json
  def update
    respond_to do |format|
      if @dojo.update(dojo_params)
        format.html { redirect_to @dojo, notice: "Dojo was successfully updated." }
        format.json { render :show, status: :ok, location: @dojo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dojo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dojos/1 or /dojos/1.json
  def destroy
    @dojo.destroy
    respond_to do |format|
      format.html { redirect_to dojos_url, notice: "Dojo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dojo
      @dojo = Dojo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dojo_params
      params.require(:dojo).permit(:name, :email, :address, :active)
    end
end

app/helpers/dojos_helper.rb
module DojosHelper
end

app/views/dojos/_form.html.erb
<body class="new_dojo">
<%= form_with(model: dojo) do |form| %>
  <% if dojo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dojo.errors.count, "error") %> prohibited this dojo from being saved:</h2>

      <ul>
        <% dojo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
<div class="col-sm"></div>
<div class="col-sm">
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-user"></i></span>
          </div>
          <%= form.text_field :name, :class => "form-control", autocomplete: "off" , placeholder: "Nombre" %>
        </div>
      </div>
      <div class="col-sm"></div>
</div>

<div class="row">
<div class="col-sm"></div>
<div class="col-sm">
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-user"></i></span>
          </div>
          <%= form.text_field :email, :class => "form-control", autocomplete: "off" , placeholder: "Correo" %>
        </div>
      </div>
      <div class="col-sm"></div>
</div>

 <div class="row">
<div class="col-sm"></div>
<div class="col-sm">
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-user"></i></span>
          </div>
          <%= form.text_field :address, :class => "form-control", autocomplete: "off" , placeholder: "Dirección" %>
        </div>
      </div>
      <div class="col-sm"></div>
</div>

<div class="row">
<div class="col-sm"></div>
   <div class="col-sm">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <div class="input-group-text">
          <%= form.check_box :active %>
          </div>
        </div>
        <%= form.label :active, :class => "form-control", autocomplete: "off" , placeholder: "Usuario activo?" %>
      </div>
    </div>
<div class="col-sm"></div>
</div>
 


  <div class="actions text-center">
      <button type="submit" class="btn btn-info btn-lg">Enviar</button>
    </div>
  </div>
  <% end %> 
  </body>
</div>

app/views/dojos/_show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @dojo.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @dojo.email %>
</p>

<p>
  <strong>Dirección:</strong>
  <%= @dojo.address %>
</p>

<p>
  <strong>Activo:</strong>
  <%= @dojo.active %>
</p>

app/views/dojos/edit.html.erb
<h1>Editando Dojo</h1>

<%= render 'form', dojo: @dojo %>

<%= link_to 'Mostrar', @dojo %> |
<%= link_to 'Atrás', dojos_path %>

app/views/dojos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dojos</h1>

<table class="table p-5">
  <thead class="thead-dark">
    <tr>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Dirección</th>
      <th>Activo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dojos.each do |dojo| %>
      <tr>
        <td><%= dojo.name %></td>
        <td><%= dojo.email %></td>
        <td><%= dojo.address %></td>
        <td><%= dojo.active %></td>
        <td><%= link_to 'Mostrar', dojo, class:'btn btn-danger', remote: true %></td>
        <td><%= link_to 'Editar', edit_dojo_path(dojo), class:'btn btn-danger' %></td>
        <td><%= link_to 'Destruir', dojo, method: :delete, data: { confirm: '¿Estás seguro?' }, class:'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Dojo', new_dojo_path, class:'btn btn-danger' %> | <%= link_to 'Atrás', info_path, class:'btn btn-danger'  %>

<div id="dojo-content"></div>

app/views/dojos/new.html.erb
<div class="text-center p-5"><h1>Nuevo Dojo</h1></div>

<%= render 'form', dojo: @dojo %>

<%= link_to 'Atrás', dojos_path %>

app/views/dojos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @dojo.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @dojo.email %>
</p>

<p>
  <strong>Dirección:</strong>
  <%= @dojo.address %>
</p>

<p>
  <strong>Activo:</strong>
  <%= @dojo.active %>
</p>

<ul>
  <% @dojo.courses.each do |course| %>
    <li><%= course.name %></li>
  <% end %>
</ul>

<%= link_to 'Editar', edit_dojo_path(@dojo) %> |
<%= link_to 'Atrás', dojos_path %>

app/views/dojos/show.js.erb
var elemento = document.querySelector('#dojo-content') 
elemento.innerHTML = "<%= escape_javascript(render partial: 'dojos/show', locals: {dojo: @dojo}) %>"