config/routes.rb
Rails.application.routes.draw do
  
  resources :courses
  resources :dojos
  devise_for :judokas, controllers: {
    registrations:'judokas/registrations',
    sessions: 'judokas/sessions' 
  }
  devise_for :senseis, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  get 'mis_senseis', to: 'senseis#index', as: 'mis_senseis'
  get 'graphics', to: 'info#graphics', as: 'graphics'
  get 'info', to: 'info#info', as: 'info'
  get 'categories', to: 'categories#index'
  get 'judo_test', to: 'judo_test#index'
  get 'judokas', to: 'judokas#index', as: 'judokas'
  get 'judokas/:id', to: 'judokas#show', as: 'judokas_show'
  get 'senseis/:id', to: 'senseis#show', as: 'senseis_show'
  get 'judo_test/:id', to: 'judo_test#show', as: 'judo_test_show'
  
  root to: "info#lobby"
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def info
    @dojos = Dojo.all
    @judokas = Judoka.all
    @senseis = Sensei.all
  end

  def lobby
  end

  def graphics
    @levels = Level.joins(:name).group('levels.name').all
    @categories = Category.joins(:name).group('categories.name').all
  end
end

app/views/info/_footer.html.erb
<div class="container-fluid">
  <footer id="contact" class="bloque1 bg-dark">
    <p class="text-center p-2"> MiDojoCR 2020.Todos los derechos reservados.
    br> 
  Costa Rica Pura Vida</p>
  </footer>
</div>

app/views/info/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <%= link_to root_path, class: 'navbar-brand' do %>
     <%= image_tag asset_path('logo.png'), size: "80x80"%>
  <% end %> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Dojos', dojos_path, class: 'nav-link active' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Cursos', courses_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Judokas', new_judoka_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Judo Tests', judo_test_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup><a class="nav-link disabled " href="#" tabindex="-1" aria-disabled="true">
      </a>
      <div class="dropdown-menu" aria-labelledby="dropdown01">
      <a class="dropdown-item" href="#">
      <% if judoka_signed_in? %>
      <%= link_to 'Desconectarse', destroy_judoka_session_path, method: :delete%>
      <% else %>
      <%= link_to '(Iniciar Sesion con Judoka)', new_judoka_session_path %>
      <%= link_to '(Iniciar Sesion con Sensei)', new_sensei_session_path %>
        <%end %>
      </div>
        </li>
      <%if current_judoka %>
      <li class="nav-item">
      <a class="nav-link disabled text-light" href="#" tabindex="-1" aria-disabled="true"><%= current_judoka.email %></a>
      </li>
      <%end%>
    </ul>
  </div>
</nav>

app/views/info/graphics.html.erb
<div class="container p-3 ">
  <div class="row border p-2">
    <div class="item col-sm-4">
      <%= pie_chart Category.group(:name).count, colors: ["#cc0000", "#b30000", "#ff7733", "#990000", "#800000", "#660000"], dataset: {borderWidth: 1.5}  %>
    <h2 class="text-center">Categorias</h2>
    </div>
    <div class="azul col-sm-8">
      <%= pie_chart Level.group(:name).count,colors: ["#800000", "#b30000", "#ffffff", "#003300", "#ff1a1a", "#ff6600", "#003399", "#ff0000", "##000000", "#1a1a1a", "#660000", "#800000", "#404040", "#ff9900"], dataset: {borderWidth: 1.5}  %>
    <h2 class="text-center">Color de Cinta</h2>
    </div>
  </div>
  <br>
  <br>
  <br>
  <div class='d-flex justify-content-around'>
    <p> ¿Con cuál usuario querés iniciar sesión?</p>
  </div>
  <div class='d-flex justify-content-around' >
    <%= link_to 'Judokas', new_judoka_registration_path, class:'btn btn-danger' %>
    <%= link_to 'Senseis', new_admin_sensei_path, class:'btn btn-danger'  %>
  </div>

app/views/info/info.html.erb
<section>
<%= render 'navbar' %>
</section>
<div>
<br>
<br>
<br>
</div>
<div class="container mt-5">
<section>
<div id="content">
  <div class="row align-self-center">
      <div class="item col-sm">
      <a href="<%= judokas_show_path(current_judoka) %>"><img src="<%= asset_path('perfil.png') %>" style="width:150px;height:150px;" alt=""></a>
      <div class='p-4'>
      <%= link_to "Mi Perfil", judokas_show_path(current_judoka), class: "btn btn-secondary p-1 my-2 mx-3"  %>
      </div>
      </div>
      <div class="item col-sm">
      <a href="<%= dojo_path(current_judoka.dojo_id) %>"><img src="<%= asset_path('dojo.png') %>" style="width:150px;height:150px;" alt=""></a>
      <div class="p-4">
      <%= link_to "Mi Dojo", dojo_path(current_judoka.dojo_id), class: "btn btn-secondary p-1 my-2 mx-3"  %>
      </div>
      </div>
      <div class="item col-sm">
      <a href="<%= mis_senseis_path %>"><img src="<%= asset_path('sensei.png') %>" style="width:150px;height:150px;" alt=""></a>
      <div class="p-4">
      <%= link_to "Mis Senseis", mis_senseis_path, class: "btn btn-secondary p-1 my-2 mx-3"  %>
      </div>
      </div>
  </div>
</div>
</div>
</div>
</section>
</div>

app/views/info/lobby.html.erb
<div class="d-flex justify-content-center p-5 float-sm-left float-md-left ">
  <div class="row">
    <div class="item col-sm-4 ml-5 ">
      <%= image_tag asset_path('logo.png'), size: "280x280"%>
    </div>
  <div class="item item-1 col-sm-7">
    <h2>BIENVENIDXS</h2>
    <h4>Mi Dojo CR</h4>
    <p>¡Estamos felices de que estés acá! <br> Creamos Mi Dojo CR, porque queríamos crear un espacio confiable e inspirador <br> con todo lo que necesitas para tener a tu alcance la información necesaria para la comunidad judoka<br>(y, aceptémoslo, porque realmente nos gusta este deporte) <br>Esperamos que navegues con mucha facilidad y encontres lo necesario.</p>
  <div class="d-flex justify-content-center">
      <%= link_to 'Gráficos', graphics_path, class:'btn btn-danger'  %>
  </div>
  </div>
  </div>
</div>  